/***************************************************************
This code was generated by Spiral 6.0 beta, www.spiral.net --
Copyright (c) 2005-2008, Carnegie Mellon University.
All rights reserved.
The code is distributed under the GNU General Public License (GPL)
(see http://www.gnu.org/copyleft/gpl.html)

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*AS IS* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************/

#include <pmmintrin.h>
#include <emmintrin.h>
#include <xmmintrin.h>
#include <mmintrin.h>

void FULL_SPIRAL(int nbits, unsigned char  *Y, unsigned char  *X, unsigned char  *syms, unsigned char  *dec, unsigned char  *Branchtab) {
    for(int i9 = 0; i9 <= (nbits/2-1); i9++) {
        unsigned char a145, a151;
        int a143, a162;
        short int s36, s37, s42, s43, s48, s49, s54
    , s55;
        unsigned char  *a144, *a150, *b12;
        short int  *a161, *a163, *a164, *a180, *a181, *a197, *a198
                , *a214, *a215;
        __m128i  *a141, *a142, *a147, *a153, *a165, *a166, *a167
                , *a168, *a169, *a172, *a182, *a183, *a184, *a185, *a186
                , *a189, *a199, *a200, *a201, *a202, *a203, *a206, *a216
                , *a217;
        __m128i a156, a157, a175, a176, a192, a193, a209
                , a210;
        __m128i a146, a148, a149, a152, a154, a155, a158
                , a159, a160, a170, a171, a173, a174, a177, a178
                , a179, a187, a188, a190, a191, a194, a195, a196
                , a204, a205, a207, a208, a211, a212, a213, d15
                , d16, d17, d18, d19, d20, d21, d22, m38
                , m39, m40, m41, m42, m43, m44, m45, m46
                , m47, m48, m49, m50, m51, m52, m53, s34
                , s35, s38, s39, s40, s41, s44, s45, s46
                , s47, s50, s51, s52, s53, s56, s57, t22
                , t23, t24, t25, t26, t27, t28, t29, t30
                , t31, t32, t33;
        a141 = ((__m128i  *) X);
        s34 = *(a141);
        a142 = (a141 + 4);
        s35 = *(a142);
        a143 = (4 * i9);
        a144 = (syms + a143);
        a145 = *(a144);
        a146 = _mm_set1_epi8(a145);
        a147 = ((__m128i  *) Branchtab);
        a148 = *(a147);
        a149 = _mm_xor_si128(a146, a148);
        b12 = (a143 + syms);
        a150 = (b12 + 1);
        a151 = *(a150);
        a152 = _mm_set1_epi8(a151);
        a153 = (a147 + 4);
        a154 = *(a153);
        a155 = _mm_xor_si128(a152, a154);
        t22 = _mm_avg_epu8(a149,a155);
        a156 = ((__m128i ) t22);
        a157 = _mm_srli_epi16(a156, 2);
        a158 = ((__m128i ) a157);
        t23 = _mm_and_si128(a158, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t24 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t23);
        m38 = _mm_adds_epu8(s34, t23);
        m39 = _mm_adds_epu8(s35, t24);
        m40 = _mm_adds_epu8(s34, t24);
        m41 = _mm_adds_epu8(s35, t23);
        a159 = _mm_min_epu8(m39, m38);
        d15 = _mm_cmpeq_epi8(a159, m39);
        a160 = _mm_min_epu8(m41, m40);
        d16 = _mm_cmpeq_epi8(a160, m41);
        s36 = _mm_movemask_epi8(_mm_unpacklo_epi8(d15,d16));
        a161 = ((short int  *) dec);
        a162 = (16 * i9);
        a163 = (a161 + a162);
        *(a163) = s36;
        s37 = _mm_movemask_epi8(_mm_unpackhi_epi8(d15,d16));
        a164 = (a163 + 1);
        *(a164) = s37;
        s38 = _mm_unpacklo_epi8(a159, a160);
        s39 = _mm_unpackhi_epi8(a159, a160);
        a165 = ((__m128i  *) Y);
        *(a165) = s38;
        a166 = (a165 + 1);
        *(a166) = s39;
        a167 = (a141 + 1);
        s40 = *(a167);
        a168 = (a141 + 5);
        s41 = *(a168);
        a169 = (a147 + 1);
        a170 = *(a169);
        a171 = _mm_xor_si128(a146, a170);
        a172 = (a147 + 5);
        a173 = *(a172);
        a174 = _mm_xor_si128(a152, a173);
        t25 = _mm_avg_epu8(a171,a174);
        a175 = ((__m128i ) t25);
        a176 = _mm_srli_epi16(a175, 2);
        a177 = ((__m128i ) a176);
        t26 = _mm_and_si128(a177, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t27 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t26);
        m42 = _mm_adds_epu8(s40, t26);
        m43 = _mm_adds_epu8(s41, t27);
        m44 = _mm_adds_epu8(s40, t27);
        m45 = _mm_adds_epu8(s41, t26);
        a178 = _mm_min_epu8(m43, m42);
        d17 = _mm_cmpeq_epi8(a178, m43);
        a179 = _mm_min_epu8(m45, m44);
        d18 = _mm_cmpeq_epi8(a179, m45);
        s42 = _mm_movemask_epi8(_mm_unpacklo_epi8(d17,d18));
        a180 = (a163 + 2);
        *(a180) = s42;
        s43 = _mm_movemask_epi8(_mm_unpackhi_epi8(d17,d18));
        a181 = (a163 + 3);
        *(a181) = s43;
        s44 = _mm_unpacklo_epi8(a178, a179);
        s45 = _mm_unpackhi_epi8(a178, a179);
        a182 = (a165 + 2);
        *(a182) = s44;
        a183 = (a165 + 3);
        *(a183) = s45;
        a184 = (a141 + 2);
        s46 = *(a184);
        a185 = (a141 + 6);
        s47 = *(a185);
        a186 = (a147 + 2);
        a187 = *(a186);
        a188 = _mm_xor_si128(a146, a187);
        a189 = (a147 + 6);
        a190 = *(a189);
        a191 = _mm_xor_si128(a152, a190);
        t28 = _mm_avg_epu8(a188,a191);
        a192 = ((__m128i ) t28);
        a193 = _mm_srli_epi16(a192, 2);
        a194 = ((__m128i ) a193);
        t29 = _mm_and_si128(a194, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t30 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t29);
        m46 = _mm_adds_epu8(s46, t29);
        m47 = _mm_adds_epu8(s47, t30);
        m48 = _mm_adds_epu8(s46, t30);
        m49 = _mm_adds_epu8(s47, t29);
        a195 = _mm_min_epu8(m47, m46);
        d19 = _mm_cmpeq_epi8(a195, m47);
        a196 = _mm_min_epu8(m49, m48);
        d20 = _mm_cmpeq_epi8(a196, m49);
        s48 = _mm_movemask_epi8(_mm_unpacklo_epi8(d19,d20));
        a197 = (a163 + 4);
        *(a197) = s48;
        s49 = _mm_movemask_epi8(_mm_unpackhi_epi8(d19,d20));
        a198 = (a163 + 5);
        *(a198) = s49;
        s50 = _mm_unpacklo_epi8(a195, a196);
        s51 = _mm_unpackhi_epi8(a195, a196);
        a199 = (a165 + 4);
        *(a199) = s50;
        a200 = (a165 + 5);
        *(a200) = s51;
        a201 = (a141 + 3);
        s52 = *(a201);
        a202 = (a141 + 7);
        s53 = *(a202);
        a203 = (a147 + 3);
        a204 = *(a203);
        a205 = _mm_xor_si128(a146, a204);
        a206 = (a147 + 7);
        a207 = *(a206);
        a208 = _mm_xor_si128(a152, a207);
        t31 = _mm_avg_epu8(a205,a208);
        a209 = ((__m128i ) t31);
        a210 = _mm_srli_epi16(a209, 2);
        a211 = ((__m128i ) a210);
        t32 = _mm_and_si128(a211, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t33 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t32);
        m50 = _mm_adds_epu8(s52, t32);
        m51 = _mm_adds_epu8(s53, t33);
        m52 = _mm_adds_epu8(s52, t33);
        m53 = _mm_adds_epu8(s53, t32);
        a212 = _mm_min_epu8(m51, m50);
        d21 = _mm_cmpeq_epi8(a212, m51);
        a213 = _mm_min_epu8(m53, m52);
        d22 = _mm_cmpeq_epi8(a213, m53);
        s54 = _mm_movemask_epi8(_mm_unpacklo_epi8(d21,d22));
        a214 = (a163 + 6);
        *(a214) = s54;
        s55 = _mm_movemask_epi8(_mm_unpackhi_epi8(d21,d22));
        a215 = (a163 + 7);
        *(a215) = s55;
        s56 = _mm_unpacklo_epi8(a212, a213);
        s57 = _mm_unpackhi_epi8(a212, a213);
        a216 = (a165 + 6);
        *(a216) = s56;
        a217 = (a165 + 7);
        *(a217) = s57;
        if ((((unsigned char  *) Y)[0]>68)) {
            __m128i m5, m6;
            m5 = ((__m128i  *) Y)[0];
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[1]);
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[2]);
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[3]);
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[4]);
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[5]);
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[6]);
            m5 = _mm_min_epu8(m5, ((__m128i  *) Y)[7]);
            __m128i m7;
            m7 = _mm_min_epu8(_mm_srli_si128(m5, 8), m5);
            m7 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m7, 32)), ((__m128i ) m7)));
            m7 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m7, 16)), ((__m128i ) m7)));
            m7 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m7, 8)), ((__m128i ) m7)));
            m7 = _mm_unpacklo_epi8(m7, m7);
            m7 = _mm_shufflelo_epi16(m7, _MM_SHUFFLE(0, 0, 0, 0));
            m6 = _mm_unpacklo_epi64(m7, m7);
            ((__m128i  *) Y)[0] = _mm_subs_epu8(((__m128i  *) Y)[0], m6);
            ((__m128i  *) Y)[1] = _mm_subs_epu8(((__m128i  *) Y)[1], m6);
            ((__m128i  *) Y)[2] = _mm_subs_epu8(((__m128i  *) Y)[2], m6);
            ((__m128i  *) Y)[3] = _mm_subs_epu8(((__m128i  *) Y)[3], m6);
            ((__m128i  *) Y)[4] = _mm_subs_epu8(((__m128i  *) Y)[4], m6);
            ((__m128i  *) Y)[5] = _mm_subs_epu8(((__m128i  *) Y)[5], m6);
            ((__m128i  *) Y)[6] = _mm_subs_epu8(((__m128i  *) Y)[6], m6);
            ((__m128i  *) Y)[7] = _mm_subs_epu8(((__m128i  *) Y)[7], m6);
        }
        unsigned char a362, a368;
        int a360, a379;
        short int s104, s105, s110, s111, s92, s93, s98
    , s99;
        unsigned char  *a361, *a367, *b29;
        short int  *a378, *a380, *a381, *a398, *a399, *a415, *a416
                , *a432, *a433, *b30;
        __m128i  *a358, *a359, *a364, *a370, *a382, *a383, *a384
                , *a385, *a387, *a390, *a400, *a401, *a402, *a403, *a404
                , *a407, *a417, *a418, *a419, *a420, *a421, *a424, *a434
                , *a435;
        __m128i a373, a374, a393, a394, a410, a411, a427
                , a428;
        __m128i a363, a365, a366, a369, a371, a372, a375
                , a376, a377, a388, a389, a391, a392, a395, a396
                , a397, a405, a406, a408, a409, a412, a413, a414
                , a422, a423, a425, a426, a429, a430, a431, d31
                , d32, d33, d34, d35, d36, d37, d38, m70
                , m71, m72, m73, m74, m75, m76, m77, m78
                , m79, m80, m81, m82, m83, m84, m85, s100
                , s101, s102, s103, s106, s107, s108, s109, s112
                , s113, s90, s91, s94, s95, s96, s97, t46
                , t47, t48, t49, t50, t51, t52, t53, t54
                , t55, t56, t57;
        a358 = ((__m128i  *) Y);
        s90 = *(a358);
        a359 = (a358 + 4);
        s91 = *(a359);
        a360 = (4 * i9);
        b29 = (a360 + syms);
        a361 = (b29 + 2);
        a362 = *(a361);
        a363 = _mm_set1_epi8(a362);
        a364 = ((__m128i  *) Branchtab);
        a365 = *(a364);
        a366 = _mm_xor_si128(a363, a365);
        a367 = (b29 + 3);
        a368 = *(a367);
        a369 = _mm_set1_epi8(a368);
        a370 = (a364 + 4);
        a371 = *(a370);
        a372 = _mm_xor_si128(a369, a371);
        t46 = _mm_avg_epu8(a366,a372);
        a373 = ((__m128i ) t46);
        a374 = _mm_srli_epi16(a373, 2);
        a375 = ((__m128i ) a374);
        t47 = _mm_and_si128(a375, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t48 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t47);
        m70 = _mm_adds_epu8(s90, t47);
        m71 = _mm_adds_epu8(s91, t48);
        m72 = _mm_adds_epu8(s90, t48);
        m73 = _mm_adds_epu8(s91, t47);
        a376 = _mm_min_epu8(m71, m70);
        d31 = _mm_cmpeq_epi8(a376, m71);
        a377 = _mm_min_epu8(m73, m72);
        d32 = _mm_cmpeq_epi8(a377, m73);
        s92 = _mm_movemask_epi8(_mm_unpacklo_epi8(d31,d32));
        a378 = ((short int  *) dec);
        a379 = (16 * i9);
        b30 = (a378 + a379);
        a380 = (b30 + 8);
        *(a380) = s92;
        s93 = _mm_movemask_epi8(_mm_unpackhi_epi8(d31,d32));
        a381 = (b30 + 9);
        *(a381) = s93;
        s94 = _mm_unpacklo_epi8(a376, a377);
        s95 = _mm_unpackhi_epi8(a376, a377);
        a382 = ((__m128i  *) X);
        *(a382) = s94;
        a383 = (a382 + 1);
        *(a383) = s95;
        a384 = (a358 + 1);
        s96 = *(a384);
        a385 = (a358 + 5);
        s97 = *(a385);
        a387 = (a364 + 1);
        a388 = *(a387);
        a389 = _mm_xor_si128(a363, a388);
        a390 = (a364 + 5);
        a391 = *(a390);
        a392 = _mm_xor_si128(a369, a391);
        t49 = _mm_avg_epu8(a389,a392);
        a393 = ((__m128i ) t49);
        a394 = _mm_srli_epi16(a393, 2);
        a395 = ((__m128i ) a394);
        t50 = _mm_and_si128(a395, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t51 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t50);
        m74 = _mm_adds_epu8(s96, t50);
        m75 = _mm_adds_epu8(s97, t51);
        m76 = _mm_adds_epu8(s96, t51);
        m77 = _mm_adds_epu8(s97, t50);
        a396 = _mm_min_epu8(m75, m74);
        d33 = _mm_cmpeq_epi8(a396, m75);
        a397 = _mm_min_epu8(m77, m76);
        d34 = _mm_cmpeq_epi8(a397, m77);
        s98 = _mm_movemask_epi8(_mm_unpacklo_epi8(d33,d34));
        a398 = (b30 + 10);
        *(a398) = s98;
        s99 = _mm_movemask_epi8(_mm_unpackhi_epi8(d33,d34));
        a399 = (b30 + 11);
        *(a399) = s99;
        s100 = _mm_unpacklo_epi8(a396, a397);
        s101 = _mm_unpackhi_epi8(a396, a397);
        a400 = (a382 + 2);
        *(a400) = s100;
        a401 = (a382 + 3);
        *(a401) = s101;
        a402 = (a358 + 2);
        s102 = *(a402);
        a403 = (a358 + 6);
        s103 = *(a403);
        a404 = (a364 + 2);
        a405 = *(a404);
        a406 = _mm_xor_si128(a363, a405);
        a407 = (a364 + 6);
        a408 = *(a407);
        a409 = _mm_xor_si128(a369, a408);
        t52 = _mm_avg_epu8(a406,a409);
        a410 = ((__m128i ) t52);
        a411 = _mm_srli_epi16(a410, 2);
        a412 = ((__m128i ) a411);
        t53 = _mm_and_si128(a412, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t54 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t53);
        m78 = _mm_adds_epu8(s102, t53);
        m79 = _mm_adds_epu8(s103, t54);
        m80 = _mm_adds_epu8(s102, t54);
        m81 = _mm_adds_epu8(s103, t53);
        a413 = _mm_min_epu8(m79, m78);
        d35 = _mm_cmpeq_epi8(a413, m79);
        a414 = _mm_min_epu8(m81, m80);
        d36 = _mm_cmpeq_epi8(a414, m81);
        s104 = _mm_movemask_epi8(_mm_unpacklo_epi8(d35,d36));
        a415 = (b30 + 12);
        *(a415) = s104;
        s105 = _mm_movemask_epi8(_mm_unpackhi_epi8(d35,d36));
        a416 = (b30 + 13);
        *(a416) = s105;
        s106 = _mm_unpacklo_epi8(a413, a414);
        s107 = _mm_unpackhi_epi8(a413, a414);
        a417 = (a382 + 4);
        *(a417) = s106;
        a418 = (a382 + 5);
        *(a418) = s107;
        a419 = (a358 + 3);
        s108 = *(a419);
        a420 = (a358 + 7);
        s109 = *(a420);
        a421 = (a364 + 3);
        a422 = *(a421);
        a423 = _mm_xor_si128(a363, a422);
        a424 = (a364 + 7);
        a425 = *(a424);
        a426 = _mm_xor_si128(a369, a425);
        t55 = _mm_avg_epu8(a423,a426);
        a427 = ((__m128i ) t55);
        a428 = _mm_srli_epi16(a427, 2);
        a429 = ((__m128i ) a428);
        t56 = _mm_and_si128(a429, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
        t57 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t56);
        m82 = _mm_adds_epu8(s108, t56);
        m83 = _mm_adds_epu8(s109, t57);
        m84 = _mm_adds_epu8(s108, t57);
        m85 = _mm_adds_epu8(s109, t56);
        a430 = _mm_min_epu8(m83, m82);
        d37 = _mm_cmpeq_epi8(a430, m83);
        a431 = _mm_min_epu8(m85, m84);
        d38 = _mm_cmpeq_epi8(a431, m85);
        s110 = _mm_movemask_epi8(_mm_unpacklo_epi8(d37,d38));
        a432 = (b30 + 14);
        *(a432) = s110;
        s111 = _mm_movemask_epi8(_mm_unpackhi_epi8(d37,d38));
        a433 = (b30 + 15);
        *(a433) = s111;
        s112 = _mm_unpacklo_epi8(a430, a431);
        s113 = _mm_unpackhi_epi8(a430, a431);
        a434 = (a382 + 6);
        *(a434) = s112;
        a435 = (a382 + 7);
        *(a435) = s113;
        if ((((unsigned char  *) X)[0]>68)) {
            __m128i m12, m13;
            m12 = ((__m128i  *) X)[0];
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[1]);
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[2]);
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[3]);
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[4]);
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[5]);
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[6]);
            m12 = _mm_min_epu8(m12, ((__m128i  *) X)[7]);
            __m128i m14;
            m14 = _mm_min_epu8(_mm_srli_si128(m12, 8), m12);
            m14 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m14, 32)), ((__m128i ) m14)));
            m14 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m14, 16)), ((__m128i ) m14)));
            m14 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m14, 8)), ((__m128i ) m14)));
            m14 = _mm_unpacklo_epi8(m14, m14);
            m14 = _mm_shufflelo_epi16(m14, _MM_SHUFFLE(0, 0, 0, 0));
            m13 = _mm_unpacklo_epi64(m14, m14);
            ((__m128i  *) X)[0] = _mm_subs_epu8(((__m128i  *) X)[0], m13);
            ((__m128i  *) X)[1] = _mm_subs_epu8(((__m128i  *) X)[1], m13);
            ((__m128i  *) X)[2] = _mm_subs_epu8(((__m128i  *) X)[2], m13);
            ((__m128i  *) X)[3] = _mm_subs_epu8(((__m128i  *) X)[3], m13);
            ((__m128i  *) X)[4] = _mm_subs_epu8(((__m128i  *) X)[4], m13);
            ((__m128i  *) X)[5] = _mm_subs_epu8(((__m128i  *) X)[5], m13);
            ((__m128i  *) X)[6] = _mm_subs_epu8(((__m128i  *) X)[6], m13);
            ((__m128i  *) X)[7] = _mm_subs_epu8(((__m128i  *) X)[7], m13);
        }
    }
    unsigned char a563, a569;
    short int s148, s149, s154, s155, s160, s161, s166
    , s167;
    unsigned char  *a562, *a568;
    short int  *a579, *a580, *a581, *a597, *a598, *a614, *a615
            , *a631, *a632;
    __m128i  *a560, *a561, *a565, *a571, *a582, *a583, *a584
            , *a585, *a586, *a589, *a599, *a600, *a601, *a602, *a603
            , *a606, *a616, *a617, *a618, *a619, *a620, *a623, *a633
            , *a634;
    __m128i a574, a575, a592, a593, a609, a610, a626
            , a627;
    __m128i a564, a566, a567, a570, a572, a573, a576
            , a577, a578, a587, a588, a590, a591, a594, a595
            , a596, a604, a605, a607, a608, a611, a612, a613
            , a621, a622, a624, a625, a628, a629, a630, d47
            , d48, d49, d50, d51, d52, d53, d54, m102
            , m103, m104, m105, m106, m107, m108, m109, m110
            , m111, m112, m113, m114, m115, m116, m117, s146
            , s147, s150, s151, s152, s153, s156, s157, s158
            , s159, s162, s163, s164, s165, s168, s169, t70
            , t71, t72, t73, t74, t75, t76, t77, t78
            , t79, t80, t81;
    a560 = ((__m128i  *) X);
    s146 = *(a560);
    a561 = (a560 + 4);
    s147 = *(a561);
    a562 = (syms + 4108);
    a563 = *(a562);
    a564 = _mm_set1_epi8(a563);
    a565 = ((__m128i  *) Branchtab);
    a566 = *(a565);
    a567 = _mm_xor_si128(a564, a566);
    a568 = (syms + 4109);
    a569 = *(a568);
    a570 = _mm_set1_epi8(a569);
    a571 = (a565 + 4);
    a572 = *(a571);
    a573 = _mm_xor_si128(a570, a572);
    t70 = _mm_avg_epu8(a567,a573);
    a574 = ((__m128i ) t70);
    a575 = _mm_srli_epi16(a574, 2);
    a576 = ((__m128i ) a575);
    t71 = _mm_and_si128(a576, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
    t72 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t71);
    m102 = _mm_adds_epu8(s146, t71);
    m103 = _mm_adds_epu8(s147, t72);
    m104 = _mm_adds_epu8(s146, t72);
    m105 = _mm_adds_epu8(s147, t71);
    a577 = _mm_min_epu8(m103, m102);
    d47 = _mm_cmpeq_epi8(a577, m103);
    a578 = _mm_min_epu8(m105, m104);
    d48 = _mm_cmpeq_epi8(a578, m105);
    s148 = _mm_movemask_epi8(_mm_unpacklo_epi8(d47,d48));
    a579 = ((short int  *) dec);
    a580 = (a579 + 16432);
    *(a580) = s148;
    s149 = _mm_movemask_epi8(_mm_unpackhi_epi8(d47,d48));
    a581 = (a579 + 16433);
    *(a581) = s149;
    s150 = _mm_unpacklo_epi8(a577, a578);
    s151 = _mm_unpackhi_epi8(a577, a578);
    a582 = ((__m128i  *) Y);
    *(a582) = s150;
    a583 = (a582 + 1);
    *(a583) = s151;
    a584 = (a560 + 1);
    s152 = *(a584);
    a585 = (a560 + 5);
    s153 = *(a585);
    a586 = (a565 + 1);
    a587 = *(a586);
    a588 = _mm_xor_si128(a564, a587);
    a589 = (a565 + 5);
    a590 = *(a589);
    a591 = _mm_xor_si128(a570, a590);
    t73 = _mm_avg_epu8(a588,a591);
    a592 = ((__m128i ) t73);
    a593 = _mm_srli_epi16(a592, 2);
    a594 = ((__m128i ) a593);
    t74 = _mm_and_si128(a594, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
    t75 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t74);
    m106 = _mm_adds_epu8(s152, t74);
    m107 = _mm_adds_epu8(s153, t75);
    m108 = _mm_adds_epu8(s152, t75);
    m109 = _mm_adds_epu8(s153, t74);
    a595 = _mm_min_epu8(m107, m106);
    d49 = _mm_cmpeq_epi8(a595, m107);
    a596 = _mm_min_epu8(m109, m108);
    d50 = _mm_cmpeq_epi8(a596, m109);
    s154 = _mm_movemask_epi8(_mm_unpacklo_epi8(d49,d50));
    a597 = (a579 + 16434);
    *(a597) = s154;
    s155 = _mm_movemask_epi8(_mm_unpackhi_epi8(d49,d50));
    a598 = (a579 + 16435);
    *(a598) = s155;
    s156 = _mm_unpacklo_epi8(a595, a596);
    s157 = _mm_unpackhi_epi8(a595, a596);
    a599 = (a582 + 2);
    *(a599) = s156;
    a600 = (a582 + 3);
    *(a600) = s157;
    a601 = (a560 + 2);
    s158 = *(a601);
    a602 = (a560 + 6);
    s159 = *(a602);
    a603 = (a565 + 2);
    a604 = *(a603);
    a605 = _mm_xor_si128(a564, a604);
    a606 = (a565 + 6);
    a607 = *(a606);
    a608 = _mm_xor_si128(a570, a607);
    t76 = _mm_avg_epu8(a605,a608);
    a609 = ((__m128i ) t76);
    a610 = _mm_srli_epi16(a609, 2);
    a611 = ((__m128i ) a610);
    t77 = _mm_and_si128(a611, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
    t78 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t77);
    m110 = _mm_adds_epu8(s158, t77);
    m111 = _mm_adds_epu8(s159, t78);
    m112 = _mm_adds_epu8(s158, t78);
    m113 = _mm_adds_epu8(s159, t77);
    a612 = _mm_min_epu8(m111, m110);
    d51 = _mm_cmpeq_epi8(a612, m111);
    a613 = _mm_min_epu8(m113, m112);
    d52 = _mm_cmpeq_epi8(a613, m113);
    s160 = _mm_movemask_epi8(_mm_unpacklo_epi8(d51,d52));
    a614 = (a579 + 16436);
    *(a614) = s160;
    s161 = _mm_movemask_epi8(_mm_unpackhi_epi8(d51,d52));
    a615 = (a579 + 16437);
    *(a615) = s161;
    s162 = _mm_unpacklo_epi8(a612, a613);
    s163 = _mm_unpackhi_epi8(a612, a613);
    a616 = (a582 + 4);
    *(a616) = s162;
    a617 = (a582 + 5);
    *(a617) = s163;
    a618 = (a560 + 3);
    s164 = *(a618);
    a619 = (a560 + 7);
    s165 = *(a619);
    a620 = (a565 + 3);
    a621 = *(a620);
    a622 = _mm_xor_si128(a564, a621);
    a623 = (a565 + 7);
    a624 = *(a623);
    a625 = _mm_xor_si128(a570, a624);
    t79 = _mm_avg_epu8(a622,a625);
    a626 = ((__m128i ) t79);
    a627 = _mm_srli_epi16(a626, 2);
    a628 = ((__m128i ) a627);
    t80 = _mm_and_si128(a628, _mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63));
    t81 = _mm_subs_epu8(_mm_set_epi8(63, 63, 63, 63, 63, 63, 63
    , 63, 63, 63, 63, 63, 63, 63, 63
    , 63), t80);
    m114 = _mm_adds_epu8(s164, t80);
    m115 = _mm_adds_epu8(s165, t81);
    m116 = _mm_adds_epu8(s164, t81);
    m117 = _mm_adds_epu8(s165, t80);
    a629 = _mm_min_epu8(m115, m114);
    d53 = _mm_cmpeq_epi8(a629, m115);
    a630 = _mm_min_epu8(m117, m116);
    d54 = _mm_cmpeq_epi8(a630, m117);
    s166 = _mm_movemask_epi8(_mm_unpacklo_epi8(d53,d54));
    a631 = (a579 + 16438);
    *(a631) = s166;
    s167 = _mm_movemask_epi8(_mm_unpackhi_epi8(d53,d54));
    a632 = (a579 + 16439);
    *(a632) = s167;
    s168 = _mm_unpacklo_epi8(a629, a630);
    s169 = _mm_unpackhi_epi8(a629, a630);
    a633 = (a582 + 6);
    *(a633) = s168;
    a634 = (a582 + 7);
    *(a634) = s169;
    if ((((unsigned char  *) Y)[0]>68)) {
        __m128i m19, m20;
        m19 = ((__m128i  *) Y)[0];
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[1]);
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[2]);
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[3]);
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[4]);
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[5]);
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[6]);
        m19 = _mm_min_epu8(m19, ((__m128i  *) Y)[7]);
        __m128i m21;
        m21 = _mm_min_epu8(_mm_srli_si128(m19, 8), m19);
        m21 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m21, 32)), ((__m128i ) m21)));
        m21 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m21, 16)), ((__m128i ) m21)));
        m21 = ((__m128i ) _mm_min_epu8(((__m128i ) _mm_srli_epi64(m21, 8)), ((__m128i ) m21)));
        m21 = _mm_unpacklo_epi8(m21, m21);
        m21 = _mm_shufflelo_epi16(m21, _MM_SHUFFLE(0, 0, 0, 0));
        m20 = _mm_unpacklo_epi64(m21, m21);
        ((__m128i  *) Y)[0] = _mm_subs_epu8(((__m128i  *) Y)[0], m20);
        ((__m128i  *) Y)[1] = _mm_subs_epu8(((__m128i  *) Y)[1], m20);
        ((__m128i  *) Y)[2] = _mm_subs_epu8(((__m128i  *) Y)[2], m20);
        ((__m128i  *) Y)[3] = _mm_subs_epu8(((__m128i  *) Y)[3], m20);
        ((__m128i  *) Y)[4] = _mm_subs_epu8(((__m128i  *) Y)[4], m20);
        ((__m128i  *) Y)[5] = _mm_subs_epu8(((__m128i  *) Y)[5], m20);
        ((__m128i  *) Y)[6] = _mm_subs_epu8(((__m128i  *) Y)[6], m20);
        ((__m128i  *) Y)[7] = _mm_subs_epu8(((__m128i  *) Y)[7], m20);
    }
}
